name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, ruby: 2.0.0 }
          - { os: ubuntu-24.04, ruby: 2.1 }
          - { os: ubuntu-24.04, ruby: 2.3 }
          - { os: ubuntu-24.04, ruby: 2.4 }
          - { os: ubuntu-24.04, ruby: 2.5 }
          - { os: ubuntu-24.04, ruby: 2.6 }
          - { os: ubuntu-24.04, ruby: 2.7 }
          - { os: ubuntu-24.04, ruby: '3.0' }
          - { os: ubuntu-24.04, ruby: 3.1 }
          - { os: ubuntu-26.04, ruby: 3.2 }
          - { os: ubuntu-26.04, ruby: 3.3 }
          - { os: ubuntu-26.04, ruby: 3.4 }
          - { os: ubuntu-26.04, ruby: "4.0" }
          - { os: ubuntu-24.04, ruby: jruby-9.3 }
          - { os: ubuntu-26.04, ruby: jruby-9.4 }
          - { os: ubuntu-26.04, ruby: jruby-10.0 }
          - { os: ubuntu-26.04, ruby: jruby-10.1 }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake spec
